# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM google/cloud-sdk:500.0.0@sha256:38eb06b9382439803f9cf546b283ec48e929d55e3824bb786984e596ee45b6da
RUN apt-get install -y netcat-traditional
