# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM google/cloud-sdk:458.0.0@sha256:b77ed10e45e0727379b874771fb86eefbd19563c2810c88f901da52747d013ac
RUN apt-get install -y netcat
