# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM google/cloud-sdk:461.0.0@sha256:4c91d8afa2013f71bdbd5e64f5c0a5b2fed6a6a7fe43c79e7bbc46ddff7c86a8
RUN apt-get install -y netcat
